# -*- coding: utf-8 -*-
"""SDG-based predictive warmer for cross-step MCP prewarming.

This module implements a lightweight first-order Markov predictor over
server/state transitions generated by the Context2SDG pipeline.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from .._logging import logger


_DEFAULT_TRANSITION_MATRIX_FILE = (
    Path(__file__).resolve().parents[3]
    / "laplace"
    / "mcp_dataset"
    / "laplace_sdg_transition_matrices.json"
)
_DEFAULT_TRACES_FILE = (
    Path(__file__).resolve().parents[3]
    / "laplace"
    / "mcp_dataset"
    / "laplace_sdg_traces.json"
)
_DEFAULT_LAPLACE_MANIFEST_FILE = (
    Path(__file__).resolve().parent
    / "server_config"
    / "laplace_mcp_manifest.json"
)
_TERMINAL_SERVER_LABELS = {"END", "__END__", "[END]"}


class MCPPredictiveWarmer:
    """Predict next MCP servers/states from SDG transition statistics.

    The warmer is designed for Contribution-2 style proactive prewarming,
    where server transitions are predicted across tool steps.

    Args:
        transition_matrix_path (`str | Path | None`, optional):
            Path to `laplace_sdg_transition_matrices.json`. When omitted, the
            default dataset location is used.
        traces_path (`str | Path | None`, optional):
            Optional fallback path to `laplace_sdg_traces.json`.
            If the matrix file is unavailable, transitions are built from
            traces on startup.
        top_k (`int`, optional):
            Maximum number of returned candidates for each prediction.
        probability_threshold (`float`, optional):
            Minimum transition probability to keep a candidate.
        include_self_transition (`bool`, optional):
            Whether to keep transitions like `A -> A`.
    """

    def __init__(
        self,
        transition_matrix_path: str | Path | None = None,
        traces_path: str | Path | None = None,
        top_k: int = 1,
        probability_threshold: float = 0.0,
        include_self_transition: bool = True,
        manifest_path: str | Path | None = None,
        server_aliases: dict[str, str] | None = None,
    ) -> None:
        """Initialize the predictive warmer.

        Args:
            transition_matrix_path (`str | Path | None`, optional):
                Path to transition matrix JSON.
            traces_path (`str | Path | None`, optional):
                Path to traces JSON used as fallback.
            top_k (`int`, optional):
                Max number of predictions.
            probability_threshold (`float`, optional):
                Candidate probability floor.
            include_self_transition (`bool`, optional):
                Keep `server -> same server` candidates when true.
            manifest_path (`str | Path | None`, optional):
                Optional Laplace manifest path used to build alias mapping
                from client/container names to canonical server names.
            server_aliases (`dict[str, str] | None`, optional):
                Additional alias mapping where key is observed name and value
                is canonical server name.
        """
        self._transition_matrix_path = Path(
            transition_matrix_path or _DEFAULT_TRANSITION_MATRIX_FILE,
        )
        self._traces_path = Path(traces_path or _DEFAULT_TRACES_FILE)
        self._top_k = max(1, int(top_k))
        self._probability_threshold = max(0.0, float(probability_threshold))
        self._include_self_transition = bool(include_self_transition)
        self._manifest_path = Path(
            manifest_path or _DEFAULT_LAPLACE_MANIFEST_FILE,
        )

        self._server_transition_counts: dict[str, dict[str, int]] = {}
        self._server_transition_matrix: dict[str, dict[str, float]] = {}
        self._state_transition_counts: dict[str, dict[str, int]] = {}
        self._state_transition_matrix: dict[str, dict[str, float]] = {}
        self._server_aliases: dict[str, str] = {}

        self._load_transitions()
        self._load_server_aliases(server_aliases)

    @classmethod
    def from_json(
        cls,
        path: str | Path,
        top_k: int = 1,
        probability_threshold: float = 0.0,
        include_self_transition: bool = True,
    ) -> "MCPPredictiveWarmer":
        """Build a predictive warmer from one transition-matrix JSON file.

        Args:
            path (`str | Path`):
                Transition-matrix JSON path.
            top_k (`int`, optional):
                Max number of predictions.
            probability_threshold (`float`, optional):
                Candidate probability floor.
            include_self_transition (`bool`, optional):
                Keep `server -> same server` candidates when true.

        Returns:
            `MCPPredictiveWarmer`:
                Configured predictive warmer instance.
        """
        return cls(
            transition_matrix_path=path,
            top_k=top_k,
            probability_threshold=probability_threshold,
            include_self_transition=include_self_transition,
        )

    def __call__(self, current_server: str | None) -> list[str]:
        """Predict server candidates from the current server label.

        Args:
            current_server (`str | None`):
                Current server name in the SDG path.

        Returns:
            `list[str]`:
                Predicted next-server labels sorted by probability.
        """
        return self.predict_next_servers(current_server=current_server)

    def predict_next_servers(
        self,
        current_server: str | None = None,
        recent_server_path: list[str] | None = None,
        top_k: int | None = None,
        probability_threshold: float | None = None,
    ) -> list[str]:
        """Predict next server candidates using server transition matrix.

        Args:
            current_server (`str | None`, optional):
                Current server label.
            recent_server_path (`list[str] | None`, optional):
                Optional server path; if provided, the last element is used as
                current server.
            top_k (`int | None`, optional):
                Optional call-level max number of predictions.
            probability_threshold (`float | None`, optional):
                Optional call-level candidate probability floor.

        Returns:
            `list[str]`:
                Sorted server candidates.
        """
        source_server = current_server
        if recent_server_path:
            source_server = recent_server_path[-1]
        if not source_server:
            return []

        canonical_source = self._canonical_server_name(source_server)

        transitions = self._server_transition_matrix.get(canonical_source)
        if not transitions and canonical_source != source_server:
            transitions = self._server_transition_matrix.get(source_server)
            canonical_source = source_server

        if not transitions:
            return []

        return self._select_candidates(
            source=canonical_source,
            transitions=transitions,
            top_k=top_k,
            probability_threshold=probability_threshold,
        )

    def predict_next_states(
        self,
        current_state: str | None,
        top_k: int | None = None,
        probability_threshold: float | None = None,
    ) -> list[str]:
        """Predict next state candidates using state transition matrix.

        Args:
            current_state (`str | None`):
                Current state label, e.g. `Maps::Search`.
            top_k (`int | None`, optional):
                Optional call-level max number of predictions.
            probability_threshold (`float | None`, optional):
                Optional call-level candidate probability floor.

        Returns:
            `list[str]`:
                Sorted state candidates.
        """
        if not current_state:
            return []

        transitions = self._state_transition_matrix.get(current_state)
        if not transitions:
            return []

        return self._select_candidates(
            source=current_state,
            transitions=transitions,
            top_k=top_k,
            probability_threshold=probability_threshold,
            terminal_labels={"END", "__END__", "[END]"},
        )

    def update_transition(self, current_server: str, next_server: str) -> None:
        """Update server transition counts with one online observation.

        Args:
            current_server (`str`):
                Source server label.
            next_server (`str`):
                Destination server label.

        Returns:
            `None`:
                Internal count and probability tables are updated in-place.
        """
        current = self._canonical_server_name(current_server.strip())
        nxt = self._canonical_server_name(next_server.strip())
        if not current or not nxt:
            return

        bucket = self._server_transition_counts.setdefault(current, {})
        bucket[nxt] = int(bucket.get(nxt, 0)) + 1
        self._server_transition_matrix[current] = self._normalize_distribution(bucket)

    @property
    def server_transition_matrix(self) -> dict[str, dict[str, float]]:
        """Expose server transition probabilities.

        Returns:
            `dict[str, dict[str, float]]`:
                Server transition matrix.
        """
        return self._server_transition_matrix

    @property
    def state_transition_matrix(self) -> dict[str, dict[str, float]]:
        """Expose state transition probabilities.

        Returns:
            `dict[str, dict[str, float]]`:
                State transition matrix.
        """
        return self._state_transition_matrix

    def _load_transitions(self) -> None:
        """Load transition tables from matrices or traces.

        Returns:
            `None`:
                Internal transition tables are initialized.
        """
        if self._transition_matrix_path.exists():
            payload = json.loads(self._transition_matrix_path.read_text(encoding="utf-8"))
            self._server_transition_counts = self._coerce_count_table(
                payload.get("server_transition_counts", {}),
            )
            self._state_transition_counts = self._coerce_count_table(
                payload.get("state_transition_counts", {}),
            )

            self._server_transition_matrix = self._coerce_probability_table(
                payload.get("server_transition_matrix", {}),
            )
            self._state_transition_matrix = self._coerce_probability_table(
                payload.get("state_transition_matrix", {}),
            )
            logger.info(
                "[PredictiveWarmer] loaded transition matrices from '%s'.",
                self._transition_matrix_path,
            )
            return

        if self._traces_path.exists():
            traces_payload = json.loads(self._traces_path.read_text(encoding="utf-8"))
            traces = traces_payload.get("traces", [])
            self._build_from_traces(traces)
            logger.info(
                "[PredictiveWarmer] built transitions from traces '%s'.",
                self._traces_path,
            )
            return

        logger.warning(
            "[PredictiveWarmer] no SDG matrices or traces found (matrices='%s', traces='%s').",
            self._transition_matrix_path,
            self._traces_path,
        )

    def _load_server_aliases(
        self,
        server_aliases: dict[str, str] | None = None,
    ) -> None:
        """Load alias mapping from optional manifest and explicit overrides.

        Args:
            server_aliases (`dict[str, str] | None`, optional):
                Explicit alias mapping where key is observed name and value
                is canonical server name.

        Returns:
            `None`:
                Alias table is updated in-place.
        """
        if self._manifest_path.exists():
            try:
                payload = json.loads(self._manifest_path.read_text(encoding="utf-8"))
                servers = payload.get("servers", {})
                if isinstance(servers, dict):
                    for server_name, server_payload in servers.items():
                        canonical_name = str(server_name).strip()
                        if not canonical_name:
                            continue
                        self._server_aliases[canonical_name] = canonical_name

                        if not isinstance(server_payload, dict):
                            continue
                        server_config = server_payload.get("server_config", {})
                        if not isinstance(server_config, dict):
                            continue

                        for key in ("client_name", "container_name"):
                            alias = str(server_config.get(key, "")).strip()
                            if alias:
                                self._server_aliases[alias] = canonical_name
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "[PredictiveWarmer] failed to parse manifest '%s': %s",
                    self._manifest_path,
                    exc,
                )

        if server_aliases:
            for alias, canonical in server_aliases.items():
                alias_name = str(alias).strip()
                canonical_name = str(canonical).strip()
                if alias_name and canonical_name:
                    self._server_aliases[alias_name] = canonical_name

    def _canonical_server_name(self, server_name: str) -> str:
        """Resolve one observed server name to canonical server name.

        Args:
            server_name (`str`):
                Observed server/client/container name.

        Returns:
            `str`:
                Canonical server name when alias is known, otherwise original
                input name.
        """
        return self._server_aliases.get(server_name, server_name)

    def _build_from_traces(self, traces: list[dict[str, Any]]) -> None:
        """Build transition tables from SDG traces.

        Args:
            traces (`list[dict[str, Any]]`):
                SDG trace records loaded from `laplace_sdg_traces.json`.

        Returns:
            `None`:
                Internal transition tables are initialized.
        """
        server_counts: dict[str, dict[str, int]] = defaultdict(dict)
        state_counts: dict[str, dict[str, int]] = defaultdict(dict)

        for trace in traces:
            summary = trace.get("sdg_summary", {})
            server_path = [str(item) for item in summary.get("server_path", []) if item]
            state_path = [str(item) for item in summary.get("state_path", []) if item]

            for source, target in zip(server_path, server_path[1:]):
                server_bucket = server_counts[source]
                server_bucket[target] = int(server_bucket.get(target, 0)) + 1

            for source, target in zip(state_path, state_path[1:]):
                state_bucket = state_counts[source]
                state_bucket[target] = int(state_bucket.get(target, 0)) + 1

        self._server_transition_counts = {
            source: dict(targets)
            for source, targets in server_counts.items()
        }
        self._state_transition_counts = {
            source: dict(targets)
            for source, targets in state_counts.items()
        }
        self._server_transition_matrix = {
            source: self._normalize_distribution(targets)
            for source, targets in self._server_transition_counts.items()
        }
        self._state_transition_matrix = {
            source: self._normalize_distribution(targets)
            for source, targets in self._state_transition_counts.items()
        }

    def _select_candidates(
        self,
        source: str,
        transitions: dict[str, float],
        top_k: int | None,
        probability_threshold: float | None,
        terminal_labels: set[str] | None = None,
    ) -> list[str]:
        """Select transition candidates by probability and policy.

        Args:
            source (`str`):
                Source label for transition lookup.
            transitions (`dict[str, float]`):
                Candidate transition probabilities.
            top_k (`int | None`):
                Candidate count cap.
            probability_threshold (`float | None`):
                Candidate probability floor.
            terminal_labels (`set[str] | None`, optional):
                Labels to skip as terminal pseudo-states.

        Returns:
            `list[str]`:
                Sorted candidate labels.
        """
        threshold = (
            self._probability_threshold
            if probability_threshold is None
            else max(0.0, float(probability_threshold))
        )
        candidate_top_k = self._top_k if top_k is None else max(1, int(top_k))
        skip_terminals = terminal_labels or _TERMINAL_SERVER_LABELS

        ranked = sorted(
            ((target, float(prob)) for target, prob in transitions.items()),
            key=lambda item: item[1],
            reverse=True,
        )

        selected: list[str] = []
        for target, probability in ranked:
            if probability < threshold:
                continue
            if target in skip_terminals:
                continue
            if not self._include_self_transition and target == source:
                continue
            selected.append(target)
            if len(selected) >= candidate_top_k:
                break

        return selected

    @staticmethod
    def _coerce_count_table(payload: Any) -> dict[str, dict[str, int]]:
        """Convert arbitrary payload into a count-table dict.

        Args:
            payload (`Any`):
                Raw JSON payload.

        Returns:
            `dict[str, dict[str, int]]`:
                Normalized nested count table.
        """
        if not isinstance(payload, dict):
            return {}

        normalized: dict[str, dict[str, int]] = {}
        for source, raw_targets in payload.items():
            if not isinstance(raw_targets, dict):
                continue
            bucket: dict[str, int] = {}
            for target, raw_count in raw_targets.items():
                try:
                    bucket[str(target)] = int(raw_count)
                except (TypeError, ValueError):
                    continue
            if bucket:
                normalized[str(source)] = bucket
        return normalized

    @staticmethod
    def _coerce_probability_table(payload: Any) -> dict[str, dict[str, float]]:
        """Convert arbitrary payload into a probability-table dict.

        Args:
            payload (`Any`):
                Raw JSON payload.

        Returns:
            `dict[str, dict[str, float]]`:
                Normalized nested probability table.
        """
        if not isinstance(payload, dict):
            return {}

        normalized: dict[str, dict[str, float]] = {}
        for source, raw_targets in payload.items():
            if not isinstance(raw_targets, dict):
                continue
            bucket: dict[str, float] = {}
            for target, raw_prob in raw_targets.items():
                try:
                    probability = float(raw_prob)
                except (TypeError, ValueError):
                    continue
                if probability < 0.0:
                    continue
                bucket[str(target)] = probability
            if bucket:
                normalized[str(source)] = bucket
        return normalized

    @staticmethod
    def _normalize_distribution(counts: dict[str, int]) -> dict[str, float]:
        """Normalize one count distribution into probabilities.

        Args:
            counts (`dict[str, int]`):
                Transition counts for one source label.

        Returns:
            `dict[str, float]`:
                Probability distribution with sum near 1.
        """
        total = float(sum(max(0, int(value)) for value in counts.values()))
        if total <= 0.0:
            return {}
        return {
            key: max(0, int(value)) / total
            for key, value in counts.items()
            if int(value) > 0
        }
